server:
  port: 8081

spring:
  resources:
    static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: mapper/HumitureMapper.xml
  type-aliases-package: com.hunau.springboot.domain

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
